name: CI

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
#      - name: Setup Node.js environment
#       uses: actions/setup-node@v3.6.0
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.4
        with:
          # GitHub token
          token: ${{ secrets.PAT_TOKEN }} 
          publish_dir: ./build
